--- #YAML:1.0
name:                Compress-LZMA-External
version:             0.35
abstract:            Compress and decompress using LZMA
license:             perl
author:              
    - Leon Brocard <acme@astray.com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    File::Temp:                    0.19
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
